mysql:
  host: "localhost"
  port: 3306
  user: "deathban"
  password: "supersecret"
  database: "deathban"

messages:
  no_permission: "&cNie masz uprawnień."
  usage: "&7Użycie: &f/deathban <unban|unbanall|checkban> [gracz]"
  unbanall: "&aOdbanowano wszystkich (&e%0&a)"
  no_player: "&cPodaj nick gracza."
  not_banned: "&cGracz &e%0 &cnie jest zbanowany."
  unban: "&aGracz &e%0 &azostał odbanowany."
  ban_check: "&e%0 &ajest zbanowany do &b%1"
  reload: "&aKonfiguracja została przeładowana."
  error: "&cWystąpił błąd: &e%0"

  # Obsługa banów po śmierci ↓
  already_banned: "&cGracz &e%0 &cjest już zbanowany."
  ban_kick: "&4&lBAN ŚMIERTELNY: &cNie możesz wejść na serwer do &e%0 &c!"
  deathban: "&cZostałeś zbanowany do &e%0&c!"
  preban_message: "&cZostałeś śmiertelnie ranny! Za &e%time% &csekund zostaniesz zbanowany po śmierci!"
  final_ban_message: "&cZostałeś zbanowany po śmierci! Powrót na serwer możliwy po &e%date%&c!"

settings:
  # czas banowania w sekundach (domyślnie: 24h)
  deathban_seconds: 86400
  # permisja na wyjątek od bana po śmierci
  exempt_permission: "deathban.vip"
  # ile sekund trwa odliczanie ostrzegawcze przed banem po śmierci
  preban_seconds: 20
  # typ wyświetlania wiadomości ostrzegawczej: "chat", "title" lub "actionbar"
  preban_display: "actionbar"
  # dźwięk podczas odliczania co sekundę
  preban_sound: "BLOCK_NOTE_BLOCK_PLING"
  # typ wyświetlania wiadomości o banie: "chat", "title" lub "actionbar"
  deathban_display: "title"
  # dźwięk przy finalnym banie po śmierci
  deathban_sound: "ENTITY_ENDER_DRAGON_GROWL"
